name = "Repos"
uuid = "952dd333-a03f-400d-b720-7cb119ba64f7"
authors = ["Thilo Gross <thilo2gross@gmail.com>"]
version = "0.1.2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
